### ISSUE TITLE
How to import a component?

### ISSUE THREAD

**Issue by jvbianchi** [johnlindquist/nuxt-typescript-starter#1]
When I try to import a component in pages/index.vue like this:

```typescript
import MyComponent from "~components/MyComponent.vue"

@Component({
  components: {
    MyComponent,
  }
})
```

I got this error:
```
error TS2307: Cannot find module '~components/MyComponent.vue'.
```

~components/MyComponent.vue:
```html
<template>
  <div>
    This is my component
  </div>
</template>
```

Am I missing anything?

**Comment by Atinux** [comment]
Does it work by importing with a relative path instead of the alias ~components?

**Comment by jvbianchi** [comment]
With relative path I got this error:
```
error TS2307: Cannot find module './../components/MyComponent.vue'.
```
import: 
```typescript
import MyComponent from "./../components/MyComponent.vue"
```

**Comment by jvbianchi** [comment]
I tried also importing without the vue extension:
```typescript
import MyComponent from "./../components/MyComponent"
```
error:
```
error TS2307: Cannot find module './../components/MyComponent'.
```

**Comment by johnlindquist** [comment]
I don't quite understand `appendTSSuffixTo`:
https://github.com/TypeStrong/ts-loader#appendtssuffixto-regexp-default

Also, every example I've read through uses `esModule:true` on the `vue-loader`:
https://github.com/vuejs/vue-class-component/blob/master/example/webpack.config.js#L24

I just don't have that much webpack experience, so trying to override the build `config` in `nuxt.config.js` just turns into guessing for me.

**Comment by jvbianchi** [comment]
Do you think adding typings like this:
```typescript
declare module '*.vue' {
	import Vue = require('vue')
	const value: Vue.ComponentOptions<Vue>
	export default value
}
```
will have any effect?

**Comment by johnlindquist** [comment]
@jvbianchi no, it's not a type error...

**Comment by johnlindquist** [comment]
@jvbianchi Try something for me:

add a `components/Foo.vue` with the following contents:
```
<template>
  <div>
    Hi
  </div>
</template>
<script lang="ts">
export default {

}
</script>
```

import it in `index.vue` with
```
import Foo from "~components/Foo"
```
and make sure to add it to 
```
@Component({
  components: {
    Foo
  },
```

If the dev server is running, _stop_ then `yarn dev` again.

Tell me if that works...

I'm thinking I've seen the following behaviors:
1. When you add a new component, you need to stop then restart the dev server
2. If you `import` without actually _using_ a component, it throws a "module not found". Do at least a `console.log(Foo)` makes this go away.

Both of those are bizarre behaviors IMO, but I don't have any answers...

**Comment by jvbianchi** [comment]
@johnlindquist when you add:
```typescript
<script lang="ts">
export default {

}
</script>
```
to any component it starts working.
I tested with:
```typescript
import MyComponent from "./../components/MyComponent.vue"
import Foo from "~components/Foo.vue";

// and

import MyComponent from "./../components/MyComponent"
import Foo from "~components/Foo";

```

In both cases work as expected.

Answering your questions: 

1. It works even without restarting the server.
2. If you don't use the component I got the error: 
```
error TS2307: Cannot find module './../components/Foo.vue'.
```
but if I `console.log(Foo)` it works.

**Comment by johnlindquist** [comment]
Great, thanks for the help.
